default: &default
  adapter: postgresql
  encoding: unicode
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
  host: ENV['DB_HOST']
  port: ENV['DB_PORT']

# development:
#   <<: *default
#   database: quizzmania_development

# test:
#   <<: *default
#   database: quizzmania_test

production:
  <<: *default
  #database: quizzmania
  database: ENV['DB_NAME']